In [1]:
list(range(3,11,2))

[3, 5, 7, 9]

In [3]:
mylist = ['a','b','c']

for name in enumerate(mylist) :
    print(name)

(0, 'a')
(1, 'b')
(2, 'c')


In [6]:
for i, name in enumerate(mylist) :
    print("{} is {}-st element".format(name, i))

a is 0-st element
b is 1-st element
c is 2-st element


In [7]:
mytable = {'Darth' : 'Father', 'Ahn' :  'actuarial'}
mytable.keys()

dict_keys(['Darth', 'Ahn'])

In [8]:
mytable.values()

dict_values(['Father', 'actuarial'])

In [10]:
mytable.items()

dict_items([('Darth', 'Father'), ('Ahn', 'actuarial')])

In [12]:
list(mytable.items())[0]

('Darth', 'Father')

In [13]:
for a,b in mytable.items() :
    print(a,b)

Darth Father
Ahn actuarial


In [15]:
list1 = [1,3,5,7]

In [16]:
list1[1:3]

[3, 5]

In [18]:
list1[1:3]  = [2,4,6]
list1

[1, 2, 4, 6, 6, 7]

In [20]:
list1[1:] + [33]+ list1[:3]

[2, 4, 6, 6, 7, 33, 1, 2, 4]

In [23]:
list1 = [1,3,5,7]

In [24]:
list2 = [1,3,5,7]

In [25]:
list1 is list2 #같지 않음

False

In [26]:
list3 = list1
list1 is list3

True

In [27]:
list1[2:3] = [100,200]

In [28]:
list1

[1, 3, 100, 200, 7]

In [29]:
list3

[1, 3, 100, 200, 7]

In [42]:
class Human() :
    def create(name2, weight2) :
            person = Human()
            person.name = name2
            person.weight = weight2
            
            return person
        
    def eat(person) :
        person.weight +=1
        print("{}s weight is {}".format(person.name, person.weight))

In [43]:
p1 = Human.create('Ahn',100)
p1.eat()

Ahns weight is 101


In [44]:
Human.eat(p1)

Ahns weight is 102


## Special function in class

In [64]:
class Human2() :
    #def __init__(self)
    
    def __init__(self, name2, weight2) :
        self.name = name2
        self.weight = weight2
        
    def __str__(self) :
        return "{}'s weight is {}".format(self.name, self.weight)
        
    
    def eat2(person):
        person.weight +=1
        print("{}'s weight is {}".format(person.name, person.weight))

In [59]:
p2 = Human2('aaa', 200)
p2.eat2()

aaa's weight is 201


In [65]:
p2

In [66]:
print(p2)

aaa's weight is 201


In [78]:
class Creature() :
    def __init__ (self, name2, weight2) :
        self.name = name2
        self.weight = weight2
        
    def eat(self) :
        self.weight +=1
        print("{}'s weight is {}".format(self.name, self.weight))

In [79]:
c1 = Creature('cre1', 500)

In [80]:
Creature.eat(c1)

cre1's weight is 501


#### Subclass(상속)

In [82]:
class Human(Creature) :
    def speak(self) :
        print("I am {}. My weight is {}." .format(self.name, self.weight))
        
        
class Animal(Creature) :
    def speak(self) :
        print("ajflkjslf")

In [84]:
h1 = Human("Ahn", 100)

In [85]:
a1 = Animal("Dog", 500)

In [86]:
h1.eat()

Ahn's weight is 101


In [87]:
a1.eat()

Dog's weight is 501


In [88]:
h1.speak()

I am Ahn. My weight is 101.


In [89]:
a1.speak()

ajflkjslf


In [90]:
Animal.eat(a1)

Dog's weight is 502


In [91]:
Animal.speak(a1)

ajflkjslf


## 조건 제시법

In [95]:
area2 = [i**2 for i in range(1,11)]
area2

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]

In [93]:
area3 = [i**2 for i in range(1,11) if i%2 ==0]
area3

[4, 16, 36, 64, 100]

In [98]:
area4 = [(x,y) for x in range (1,5) for y in range(1,5) if x%2 ==0 if y%2==0]
area4

[(2, 2), (2, 4), (4, 2), (4, 4)]

In [102]:
area5 = [(x,y) for x in range (1,5) for y in range(1,5) if x%2 ==0 and y%2==0]
area5

[(2, 2), (2, 4), (4, 2), (4, 4)]

In [104]:
students = ['a', 'b', 'c', 'd']
for number, name in enumerate(students) :
    print(number, name)


0 a
1 b
2 c
3 d


In [105]:
stu_dict = {10:'a', 20:'b', 30:'c', 40:'d'}
print(stu_dict[10])

a


In [108]:
stu_dict2 = {(number+1)*10 : name for number, name in enumerate(students)}
stu_dict2

{10: 'a', 20: 'b', 30: 'c', 40: 'd'}

In [109]:
nums = [10,20,30,40]

In [110]:
a= zip(students, nums)

In [112]:
list(a)

[('a', 10), ('b', 20), ('c', 30), ('d', 40)]

In [114]:
stu_dict3 = {x:y for x,y in zip(students, nums)}
stu_dict3

{'a': 10, 'b': 20, 'c': 30, 'd': 40}

# numpy

In [116]:
import numpy as np

In [118]:
a=[1,2,3]
a

[1, 2, 3]

In [119]:
b=np.array([1,2,3])
b

array([1, 2, 3])

In [120]:
a+3

TypeError: can only concatenate list (not "int") to list

In [121]:
b+3

array([4, 5, 6])

In [122]:
np.__version__

'1.14.3'

In [123]:
a=np.array( [i**2 for i in range(1,11)])
a

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [127]:
b = np.array( [[i,i**2] for i in range(1,11)])
b

array([[  1,   1],
       [  2,   4],
       [  3,   9],
       [  4,  16],
       [  5,  25],
       [  6,  36],
       [  7,  49],
       [  8,  64],
       [  9,  81],
       [ 10, 100]])

In [129]:
a=[ [[1,1],[10,10]],[[2,2]],[[100,100]]]

In [130]:
a

[[[1, 1], [10, 10]], [[2, 2]], [[100, 100]]]

In [131]:
a[0]

[[1, 1], [10, 10]]

In [132]:
a[1]

[[2, 2]]

In [135]:
a[0][0][0]

1

In [136]:
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [138]:
np.ones(10, dtype=int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [139]:
np.ones([3,3], dtype=int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [141]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [142]:
list(np.arange(1,11,2))

[1, 3, 5, 7, 9]

In [143]:
np.full([3,3], 500)

array([[500, 500, 500],
       [500, 500, 500],
       [500, 500, 500]])

In [144]:
np.random.random([3,3])

array([[0.61140409, 0.15438652, 0.54950844],
       [0.22350475, 0.8758778 , 0.15615476],
       [0.46730647, 0.7163487 , 0.93013362]])

In [145]:
np.random.normal(scale=10, size=[3,3])

array([[  7.92435296,   5.34510268,   9.21828994],
       [ -9.65625562,   4.98921333,  -0.22450482],
       [  7.45724614,  -2.79186459, -18.14920658]])

In [146]:
#단위행렬
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [150]:
np.empty(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [151]:
np.ones(10,dtype=float)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [152]:
np.ones(10, dtype=int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [156]:
#set.seed(500)
np.random.seed(593)
x1=np.random.randint(10, size=[2,2,2]) 
x1

array([[[7, 0],
        [8, 2]],

       [[2, 0],
        [1, 4]]])

In [157]:
x1.shape

(2, 2, 2)

In [158]:
x1.size

8

In [159]:
x1.ndim

3

In [160]:
np.shape(x1)

(2, 2, 2)

In [161]:
x=np.random.randint(10, size=[3,3])
x

array([[7, 0, 2],
       [4, 8, 9],
       [1, 2, 9]])

In [162]:
x[1, :]

array([4, 8, 9])

In [163]:
m=x[1:2,:]
m

array([[4, 8, 9]])

In [165]:
print(m.shape, m.ndim)

(1, 3) 2


In [164]:
v=x[1, :]

In [167]:
print(v.shape, v.ndim)

(3,) 1


In [169]:
x2=x
x2

array([[7, 0, 2],
       [4, 8, 9],
       [1, 2, 9]])

In [170]:
x is x2

True

In [171]:
x3= x.copy()

In [173]:
#다름
x is x3

False

In [174]:
x4 = x[:,:]

In [176]:
#내용물만 copy 다른 instance
x is x4

False

In [177]:
x5=x[0, :]
x5

array([7, 0, 2])

In [178]:
x5[np.newaxis, :]

array([[7, 0, 2]])

In [179]:
x5[:, np.newaxis]

array([[7],
       [0],
       [2]])

In [180]:
x

array([[7, 0, 2],
       [4, 8, 9],
       [1, 2, 9]])

In [185]:
x.shape

(3, 3)

In [187]:
x[np.newaxis, :, :]

array([[[7, 0, 2],
        [4, 8, 9],
        [1, 2, 9]]])

In [188]:
x[np.newaxis, :, :].shape

(1, 3, 3)

In [182]:
x[:,np.newaxis, :]

array([[[7, 0, 2]],

       [[4, 8, 9]],

       [[1, 2, 9]]])

In [190]:
x[:,np.newaxis, :].shape

(3, 1, 3)

In [183]:
x[:,:, np.newaxis]

array([[[7],
        [0],
        [2]],

       [[4],
        [8],
        [9]],

       [[1],
        [2],
        [9]]])

In [191]:
x[:,:, np.newaxis].shape

(3, 3, 1)

In [192]:
x=np.array([1,2,3])
y=np.array([4,5,6])

In [193]:
x

array([1, 2, 3])

In [194]:
y

array([4, 5, 6])

In [195]:
np.array([x,y])

array([[1, 2, 3],
       [4, 5, 6]])

In [196]:
np.concatenate([x,y])

array([1, 2, 3, 4, 5, 6])

In [199]:
xx=x.reshape([1,3])
xx

array([[1, 2, 3]])

In [200]:
yy = x.reshape([1,3])
yy

array([[1, 2, 3]])

In [202]:
np.concatenate([xx,yy])

array([[1, 2, 3],
       [1, 2, 3]])

In [203]:
np.concatenate([xx,yy],1)

array([[1, 2, 3, 1, 2, 3]])

In [204]:
np.vstack([xx,yy])

array([[1, 2, 3],
       [1, 2, 3]])

In [205]:
np.hstack([xx,yy])

array([[1, 2, 3, 1, 2, 3]])

In [206]:
t = [1,2,3,100,101,500,501,502]

In [207]:
a1,a2,a3 = np.split(t, [3,5])

In [208]:
a1

array([1, 2, 3])

In [209]:
a2

array([100, 101])

In [210]:
a3

array([500, 501, 502])

In [211]:
x

array([1, 2, 3])

In [212]:
x+4

array([5, 6, 7])

In [216]:
np.linspace(0,100,11)

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

In [218]:
np.sin(np.pi)

1.2246467991473532e-16

In [219]:
np.log(np.exp(100))

100.0

In [220]:
x

array([1, 2, 3])

In [221]:
np.add.reduce(x)

6

In [232]:
X = np.random.random([4,3])
X

array([[0.18895091, 0.89929641, 0.18081442],
       [0.11317378, 0.97788618, 0.34231208],
       [0.12288943, 0.94032344, 0.37704123],
       [0.58180333, 0.61242191, 0.65120513]])

In [234]:
np.add.reduce(X, axis = 1)

array([1.26906174, 1.43337203, 1.4402541 , 1.84543038])

In [235]:
np.mean(X, axis=1)

array([0.42302058, 0.47779068, 0.4800847 , 0.61514346])

In [236]:
np.mean(X, axis=0)

array([0.25170436, 0.85748198, 0.38784322])

## president height

In [237]:
import pandas as pd

In [239]:
height = pd.read_csv('./president_heights.csv')
height.head()

order               name  height(cm)
0      1  George Washington         189
1      2         John Adams         170
2      3   Thomas Jefferson         189
3      4      James Madison         163
4      5       James Monroe         183

In [240]:
np.mean(height['height(cm)'])

179.73809523809524

In [241]:
np.min(height['height(cm)'])

163

In [261]:
h = height['height(cm)']
h.head()

0    189
1    170
2    189
3    163
4    183
Name: height(cm), dtype: int64

In [263]:
height.iloc[h.argmin,]

C:\Users\wjssm\Anaconda3\lib\site-packages\pandas\core\common.py:405: FutureWarning: 'argmin' is deprecated, use 'idxmin' instead. The behavior of 'argmin'
will be corrected to return the positional minimum in the future.
Use 'series.values.argmin' to get the position of the minimum now.
  return maybe_callable(obj, **kwargs)


order                     4
name          James Madison
height(cm)              163
Name: 3, dtype: object

In [ ]:
np.max(height['height(cm)'])

In [256]:
height.iloc[np.argmax(height['height(cm)']),]

C:\Users\wjssm\Anaconda3\lib\site-packages\numpy\core\fromnumeric.py:52: FutureWarning: 'argmax' is deprecated, use 'idxmax' instead. The behavior of 'argmax'
will be corrected to return the positional maximum in the future.
Use 'series.values.argmax' to get the position of the maximum now.
  return getattr(obj, method)(*args, **kwds)


order                      16
name          Abraham Lincoln
height(cm)                193
Name: 15, dtype: object

In [249]:
np.std(height['height(cm)'])

6.931843442745893

In [257]:
np.percentile(height['height(cm)'],90)

188.0

# braodcasting

In [264]:
a = np.array([0,1,2])
b = np.array([5,7,9])

In [265]:
a+b

array([ 5,  8, 11])

In [269]:
x = np.ones([3,3], dtype=int)
x.shape

(3, 3)

In [271]:
y = np.array(([0],[1],[2]))
y

array([[0],
       [1],
       [2]])

In [272]:
x+y

array([[1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]])

In [274]:
x = np.array([0,1,2]).reshape(-1,1)
x

array([[0],
       [1],
       [2]])

In [275]:
y = np.array([100,200,300])
y

array([100, 200, 300])

In [276]:
x+y

array([[100, 200, 300],
       [101, 201, 301],
       [102, 202, 302]])