In [1]:
import numpy as np
import tensorflow as tf

C:\Users\wjssm\Anaconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


##### y = Xw+b

In [3]:
w = tf.Variable(tf.zeros([2,1]))
b = tf.Variable(tf.zeros([1]))

In [4]:
x = tf.placeholder(tf.float32, shape = [None,2])
#t : true
t = tf.placeholder(tf.float32, shape = [None, 1])
#y : y_hat
y = tf.sigmoid(tf.matmul(x,w)+b)

In [5]:
#실제 데이터
X = np.array([[0,0], [1,0], [0,1],[1,1]])
Y = np.array([[0],[1],[1],[1]])

### loss function

In [8]:
cross_entropy = -tf.reduce_sum(t * tf.log(y) + (1-t)*tf.log(1-y))

### optimizer

In [10]:
train_step = tf.train.GradientDescentOptimizer(0.1).minimize(cross_entropy)

In [14]:
correct_prediction = tf.equal( tf.to_float(tf.greater(y,0.5)), t) 

### variable initialization

In [7]:
sess = tf.Session()
init = tf.global_variables_initializer()
sess.run(init)

In [33]:
for epoch in range(2000) :
    sess.run(train_step, feed_dict = {
        x: X,
        t: Y
    })
    
    my_c_e = sess.run(cross_entropy, feed_dict = {
        x:X, t:Y
    })
    if epoch % 10 ==0 :
        print(-my_c_e)

-0.11808021
-0.116618544
-0.11519177
-0.11379888
-0.11243828
-0.111109495
-0.10981083
-0.10854183
-0.107301116
-0.10608792
-0.104901105
-0.10374038
-0.10260458
-0.10149251
-0.10040417
-0.09933843
-0.09829475
-0.09727207
-0.09627034
-0.09528867
-0.09432643
-0.09338313
-0.09245806
-0.09155066
-0.09066081
-0.089787975
-0.08893122
-0.08809047
-0.087265395
-0.086455055
-0.08565967
-0.08487844
-0.08411116
-0.08335726
-0.082616664
-0.08188875
-0.08117374
-0.08047054
-0.07977936
-0.079099715
-0.07843158
-0.07777427
-0.077127844
-0.07649193
-0.075865954
-0.07525029
-0.07464436
-0.07404798
-0.073460914
-0.07288283
-0.072313905
-0.07175334
-0.071201496
-0.07065806
-0.07012247
-0.06959486
-0.06907539
-0.06856321
-0.06805848
-0.06756098
-0.06707074
-0.06658758
-0.066110894
-0.06564115
-0.06517787
-0.06472111
-0.06427067
-0.06382619
-0.06338778
-0.06295533
-0.06252864
-0.062107585
-0.061691992
-0.061282083
-0.060877442
-0.06047812
-0.060083877
-0.059694707
-0.059310608
-0.0589312
-0.058556445
-0.058

In [19]:
sess.run(w)

array([[3.6118839],
       [3.6118839]], dtype=float32)

In [24]:
sess.run(y, feed_dict = {x: X, t:Y})

array([[0.22355042],
       [0.9142595 ],
       [0.9142595 ],
       [0.99747413]], dtype=float32)

In [28]:
correct_prediction.eval(session = sess, feed_dict = {
    x:X, 
    t:Y
})

array([[ True],
       [ True],
       [ True],
       [ True]])

In [29]:
sess.run(correct_prediction, feed_dict = {
    x:X,
    t:Y
})

array([[ True],
       [ True],
       [ True],
       [ True]])

In [35]:
accuracy = tf.reduce_mean(tf.cast(correct_prediction, tf.float32))
accuracy = accuracy.eval(session =sess, feed_dict = {x:X, t:Y})
accuracy

1.0

In [12]:
import numpy as np
from keras.models import Sequential
from keras.layers import Dense, Activation
from keras.optimizers import SGD

In [8]:
model = Sequential([
    
    Dense(input_dim = 2, units = 1), #XW+b
    Activation('sigmoid')
]
    
)

In [9]:
model.compile(loss = 'binary_crossentropy', optimizer=SGD(lr = 0.1))

In [13]:
X = np.array([[0,0], [1,0], [0,1],[1,1]])
Y = np.array([[0],[1],[1],[1]])

In [15]:
model.fit(X,Y, epochs=200, batch_size=4, verbose=1)

Epoch 1/200
4/4 [==============================] - 0s 650us/step - loss: 0.3184
Epoch 2/200
4/4 [==============================] - 0s 1ms/step - loss: 0.3176
Epoch 3/200
4/4 [==============================] - 0s 269us/step - loss: 0.3168
Epoch 4/200
4/4 [==============================] - 0s 1ms/step - loss: 0.3160
Epoch 5/200
4/4 [==============================] - 0s 570us/step - loss: 0.3152
Epoch 6/200
4/4 [==============================] - 0s 250us/step - loss: 0.3144
Epoch 7/200
4/4 [==============================] - 0s 1ms/step - loss: 0.3136
Epoch 8/200
4/4 [==============================] - 0s 518us/step - loss: 0.3128
Epoch 9/200
4/4 [==============================] - 0s 799us/step - loss: 0.3120
Epoch 10/200
4/4 [==============================] - 0s 354us/step - loss: 0.3112
Epoch 11/200
4/4 [==============================] - 0s 675us/step - loss: 0.3104
Epoch 12/200
4/4 [==============================] - 0s 306us/step - loss: 0.3096
Epoch 13/200
4/4 [=========================

Epoch 103/200
4/4 [==============================] - 0s 1ms/step - loss: 0.2507
Epoch 104/200
4/4 [==============================] - 0s 498us/step - loss: 0.2501
Epoch 105/200
4/4 [==============================] - 0s 715us/step - loss: 0.2496
Epoch 106/200
4/4 [==============================] - 0s 690us/step - loss: 0.2491
Epoch 107/200
4/4 [==============================] - 0s 516us/step - loss: 0.2485
Epoch 108/200
4/4 [==============================] - 0s 1ms/step - loss: 0.2480
Epoch 109/200
4/4 [==============================] - 0s 561us/step - loss: 0.2475
Epoch 110/200
4/4 [==============================] - 0s 498us/step - loss: 0.2470
Epoch 111/200
4/4 [==============================] - 0s 774us/step - loss: 0.2464
Epoch 112/200
4/4 [==============================] - 0s 0us/step - loss: 0.2459
Epoch 113/200
4/4 [==============================] - 0s 916us/step - loss: 0.2454
Epoch 114/200
4/4 [==============================] - 0s 887us/step - loss: 0.2449
Epoch 115/200
4/4 [===

In [18]:
model.fit(X,Y, epochs=1000, batch_size=4, verbose=0)

### end of learning

In [19]:
model.predict_proba(X)

array([[0.12986013],
       [0.9492495 ],
       [0.9485454 ],
       [0.99956733]], dtype=float32)

In [20]:
model.predict_classes(X)

array([[0],
       [1],
       [1],
       [1]])